import { Select } from "antd";
import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getCharacters } from "../logic/services/breakingbad";
import {
  character,
  characters,
  sortByType,
  sortFromType,
} from "../logic/types";
import styles from "../styles/Home.module.css";

const Home: NextPage = ({
  posts,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const [listBy, setListBy] = useState<characters>(posts);
  const [sortBy, setSortBy] = useState<sortByType>(undefined);
  const [sortFrom, setSortFrom] = useState<sortFromType>(undefined);
  const { Option } = Select;

  useEffect(() => {
    // sortBy &&
    //   setListBy(
    //     posts.sort((a: character, b: character) => a[sortBy] - b[sortBy])
    //   );
  }, [sortBy]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Motenro assesment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <Select style={{ width: 120 }} onChange={(value) => setSortBy(value)}>
          <Option value="name">Name</Option>
          <Option value="nickName">Nickname</Option>
          <Option value="birthday">Birthday</Option>
        </Select>
      </section>
      <section>
        <Select style={{ width: 120 }} onChange={(value) => setSortFrom(value)}>
          <Option value="start">Ascending</Option>
          <Option value="end">Descending</Option>
        </Select>
      </section>
      {posts.map((item: character, index: number) => (
        <section key={index}>
          <Link href={`/${item.name}`}>{item.name}</Link>
        </section>
      ))}
    </div>
  );
};
export const getServerSideProps: GetServerSideProps = async (context) => {
  const posts = await getCharacters();

  return {
    props: {
      posts,
    },
  };
};

export default Home;
