import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import Head from "next/head";
import Image from "next/image";
import { getCharacters } from "../logic/services/breakingbad";
import styles from "../styles/Home.module.css";

const Home: NextPage = ({
  posts,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {posts.length}
    </div>
  );
};
export const getServerSideProps: GetServerSideProps = async (context) => {
  const posts = await getCharacters();

  return {
    props: {
      posts,
    },
  };
};

export default Home;
